title: Technical Fluff
description: A part-time dog's notes on software, design, maths or whatever.
baseurl: ""
url: "https://blog.elttob.uk"

personal_name: "Elttob"
personal_url: "https://elttob.uk"

date_format: "%e %b %Y"

default_thumbnails:
  - "/assets/fallback/thumbnails/0.jpg"
  - "/assets/fallback/thumbnails/1.jpg"
  - "/assets/fallback/thumbnails/2.jpg"
  - "/assets/fallback/thumbnails/3.jpg"
  - "/assets/fallback/thumbnails/4.jpg"

footer: >-
  This is my personal blog. I don't speak for my employer. I don't write
  sponsored posts. <a href="https://github.com/sponsors/Elttob">I accept
  donations on GitHub.</a>
copyright: Text is MIT licensed unless specified; use with attribution, links are appreciated.

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag